insert into INSURANCE_PLANS(plan_id,plan_name,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_HOLDER_STATUS) values(101,'SNAP','ESU',9505899145,'APPROVED');
insert into INSURANCE_PLANS(plan_Id,plan_Name,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_HOLDER_STATUS) values(102,'CCAP','MANU',9100166404,'APPROVED');
insert into INSURANCE_PLANS(plan_Id,plan_Name,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_HOLDER_STATUS) values(103,'SNAP','RAM',966666897,'DENIED');
insert into INSURANCE_PLANS(plan_Id,plan_Name,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_HOLDER_STATUS) values(104,'SNAP','RAHUL',978793497,'APPROVED');
insert into INSURANCE_PLANS(plan_Id,plan_Name,PLAN_HOLDER_NAME,PLAN_HOLDER_SSN,PLAN_HOLDER_STATUS) values(105,'SNAP','SANDEEP',978789897,'DENIED');